name: build shared lib

on:
    push:
        branches: ["omena-main"]
    pull_request:
        branches: ["omena-main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: lib
              run: make
